### ISSUE TITLE
Not Actually Issue

### ISSUE THREAD

**Issue by KingTone2018** [payamazadi/replay-bot#1]
I am a noob with this stuff, this looks cool and I want to try it.

I believe I got correctly to the last step and I get some error I have no idea what to try next.  

There was something about skipping items on npm install unsure if that could be related. Any idea/help?
![image](https://user-images.githubusercontent.com/78120641/106071569-37299900-60cc-11eb-8034-a26869ea8ec5.png)

**Comment by payamazadi** [comment]
Hi KingTone,

Looks like you found a bug in my code! I will commit a fix now. But you can fix it easily on your end I think.

In your .env file, you probably have 
`TESTCHANNEL=`
`REALCHANNEL=`

change those to
`TESTCHANNELID=`
`REALCHANNELID=`
(adding ID at the end)

Then, if the chatroom IDs are correct, everything should work, based on what I'm seeing. Let me know if you still have trouble and I'll try and help!

**Comment by payamazadi** [comment]
The only one you need is REALCHANNELID, the channel ID of your main channel. I have a testing one for testing purposes, I think you can leave that one blank.

**Comment by KingTone2018** [comment]
Amazing, that was exactly it!

Glad I could help find the small bug. I noticed so many mistakes on my end for the config and did not notice that!

Thank you for the help.

**Comment by payamazadi** [comment]
I'm super excited it worked for you! Great work! Enjoy!
